apiVersion: v1
kind: Service
metadata:
  name: external-dns-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: external-dns
  labels:
    app: enternal-dns
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.88.50
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
  selector:
    app: external-dns
---
apiVersion: v1
kind: Service
metadata:
  name: external-dns-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: external-dns
  labels:
    app: external-dns
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.88.50
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
  selector:
    app: external-dns